#!/bin/bash

declare -r DWM_BINARY="/usr/local/bin/dwm"
declare -r DWM_LOADER=$(readlink -f $0)
declare -r DWM_LOADER_NAME=$(basename $DWM_LOADER)

# Set black background
xsetroot -solid black

# Merge X resources
xrdb -merge ~/.Xresources &

# Fix Java apps
wmname LG3D

# Start applications in ~/.dwm-start
test -e ~/.dwm-start && ~/.dwm-start &

while true; do
  $DWM_BINARY || exit;
done

exit 0
