#!/bin/bash

WEB_BROWSER="WEB_BROWSER_FROM_CONFIG"
WEB_BROWSER="google-chrome"

regexRT='^#?[0-9]{6}$'
regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
link=`xsel -o | sed "s/^[ \t]*//"`
search="http://www.google.com/search?q="

if [[ $link =~ $regexRT ]]; then
    $WEB_BROWSER "https://engineering.redhat.com/rt/Ticket/Display.html?id="$(echo "$link" | sed -r 's/#//')
elif [[ $link =~ $regex ]]; then
    $WEB_BROWSER "$link"
else
    $WEB_BROWSER "${search}${link}"
fi
