#!/bin/bash

DWM_BINARY="/usr/local/bin/dwm"

# Set black background
xsetroot -solid black

# Merge X resources
xrdb -merge ~/.Xresources &

# Fix Java apps
wmname LG3D

# Start applications in ~/.dwm-start
test -e ~/.dwm-start && ~/.dwm-start &

while true; do
  $DWM_BINARY >/dev/null 2>&1

  if [[ $? -ne 129 ]]; then
    break
  fi
done

exit 0
